### ISSUE TITLE
Cities are missing

### ISSUE THREAD

**Issue by sakerhetspolisen** [sakerhetspolisen/uv-kollen#206]
We currently need to add:
- Kungsbacka
- Saxnäs

![image](https://github.com/sakerhetspolisen/uv-kollen/assets/68159964/e3736a4c-8d22-4800-8f7e-8ea07a210b59)

**Comment by Aiiion** [comment]
Added a pull request to add Kungsbacka. It seems saxnäs already exists.
https://github.com/sakerhetspolisen/uv-kollen/pull/207

**Comment by sakerhetspolisen** [comment]
Thanks for helping @Aiiion !! Your PR has been merged and Kungsbacka is now available on UV-Kollen.
